development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  #url: redis://redistogo:33dd80b2f4777d40ff351572066aa7a4@crestfish.redistogo.com:9504/
 
  url: <%= ENV.fetch("REDIS_URL") { "redis://redistogo:33dd80b2f4777d40ff351572066aa7a4@crestfish.redistogo.com:9504/" } %>
  channel_prefix: message_me_production
